<?php
/**
 * @var  \Talexan\Credit\Block\Product\View\CoinsThatCustomerWillReceiveUponPurchase $block
 */
?>
<div class="product attribute received_coin">
    <strong class="type">
        <?php if (!$block->getCustomerIsLoggedIn()): ?>
            <p><?= __("Please, Sign In."); ?></p>
        <?php endif; ?>
        <?= __("You Will Receive up to %1 Coins for Purchasing this Product", $block->getReceivedCoin()); ?>
    </strong>
</div>
